---
- name: Check if todoapp.service is registered in systemd
  stat:
    path: /etc/systemd/system/todoapp.service
  register: file_details
- name: Templating todoapp_service.j2 to register todoapp service
  template:
    src: todoapp_service.j2
    dest: /etc/systemd/system/todoapp.service
    owner: "{{ todoapp_user_name }}"
    mode: "0755"
  when: not file_details.stat.exists
-  name: Trigger Daemon-reload, Restart todoapp.service
   command: /bin/true
   notify: Daemon-reload, Restart todoapp.service